// banco_datos.js

const bancoPotenciacion = [
    { q: "x^3 \\cdot x^4", estrategia: "Aplicar la ley de productos de bases iguales: sumar exponentes.", pasos: "1) & 3 + 4 = 7 \\\\ 2) & x^7", r: "x^7" },
    { q: "a^5 \\cdot a", estrategia: "Recordar que a = a^1. Sumar exponentes.", pasos: "1) & 5 + 1 = 6 \\\\ 2) & a^6", r: "a^6" },
    { q: "x^{-2} \\cdot x^5", estrategia: "Suma de enteros en los exponentes.", pasos: "1) & -2 + 5 = 3 \\\\ 2) & x^3", r: "x^3" },
    { q: "(2x^2)(3x^4)", estrategia: "Multiplicar coeficientes y sumar exponentes.", pasos: "1) & 2 \\cdot 3 = 6 \\\\ 2) & 2 + 4 = 6 \\\\ 3) & 6x^6", r: "6x^6" },
    { q: "\\frac{x^{10}}{x^3}", estrategia: "Ley de cocientes de bases iguales: restar exponentes.", pasos: "1) & 10 - 3 = 7 \\\\ 2) & x^7", r: "x^7" },
    { q: "\\frac{12x^6}{4x^2}", estrategia: "Dividir coeficientes y restar exponentes.", pasos: "1) & 12 / 4 = 3 \\\\ 2) & 6 - 2 = 4 \\\\ 3) & 3x^4", r: "3x^4" },
    { q: "(x^3)^2", estrategia: "Potencia de potencia: multiplicar exponentes.", pasos: "1) & 3 \\cdot 2 = 6 \\\\ 2) & x^6", r: "x^6" },
    { q: "(2x^2)^3", estrategia: "Distribuir el exponente al coeficiente y a la base.", pasos: "1) & 2^3 = 8 \\\\ 2) & (x^2)^3 = x^6 \\\\ 3) & 8x^6", r: "8x^6" },
    { q: "(xy)^4", estrategia: "Propiedad distributiva de la potencia sobre el producto.", pasos: "1) & x^4 \\cdot y^4", r: "x^4y^4" },
    { q: "x^{1/2}", estrategia: "Relación entre exponentes fraccionarios y raíces.", pasos: "1) & x^{1/2} = \\sqrt{x}", r: "\\sqrt{x}" }
];

const bancoRadicacion = [
    { q: "\\sqrt{x^2}", estrategia: "La raíz cuadrada cancela la potencia al cuadrado.", pasos: "1) & \\sqrt{x^2} = x^{2/2} \\\\ 2) & x", r: "x" },
    { q: "\\sqrt{16x^4}", estrategia: "Distribuir raíz a cada factor.", pasos: "1) & \\sqrt{16} \\cdot \\sqrt{x^4} \\\\ 2) & 4x^2", r: "4x^2" },
    { q: "\\sqrt[3]{8a^6}", estrategia: "Extraer raíz cúbica al número y dividir exponente entre 3.", pasos: "1) & \\sqrt[3]{8}=2 \\\\ 2) & a^{6/3}=a^2 \\\\ 3) & 2a^2", r: "2a^2" },
    { q: "\\sqrt[3]{x^2}", estrategia: "Convertir la raíz a exponente fraccionario.", pasos: "1) & \\text{Índice va al denominador} \\\\ 2) & x^{2/3}", r: "x^{2/3}" },
    { q: "\\sqrt{2} \\cdot \\sqrt{8}", estrategia: "Propiedad de productos de raíces de igual índice.", pasos: "1) & \\sqrt{2 \\cdot 8} = \\sqrt{16} \\\\ 2) & 4", r: "4" },
    { q: "\\sqrt{x^3}", estrategia: "Extraer la parte exacta del radical.", pasos: "1) & \\sqrt{x^2 \\cdot x} \\\\ 2) & x\\sqrt{x}", r: "x\\sqrt{x}" },
    { q: "3\\sqrt{x} + 2\\sqrt{x}", estrategia: "Reducción de términos semejantes.", pasos: "1) & (3+2)\\sqrt{x} \\\\ 2) & 5\\sqrt{x}", r: "5\\sqrt{x}" },
    { q: "(\\sqrt{a})^2", estrategia: "Definición de operación inversa.", pasos: "1) & \\sqrt{a}^2 = a", r: "a" },
    { q: "\\sqrt{18x^2}", estrategia: "Factorizar dentro de la raíz.", pasos: "1) & \\sqrt{9 \\cdot 2 \\cdot x^2} \\\\ 2) & 3x\\sqrt{2}", r: "3x\\sqrt{2}" },
    { q: "\\sqrt[3]{-1}", estrategia: "Raíz impar de un número negativo.", pasos: "1) & (-1)^3 = -1 \\\\ 2) & -1", r: "-1" }
];

const bancoLogaritmos = [
    { q: "\\log_b(x \\cdot y)", estrategia: "Propiedad del producto de logaritmos.", pasos: "1) & \\log_b(x) + \\log_b(y)", r: "\\log_b(x) + \\log_b(y)" },
    { q: "\\log_2\\left(\\frac{x}{8}\\right)", estrategia: "Propiedad del cociente de logaritmos.", pasos: "1) & \\log_2(x) - \\log_2(8) \\\\ 2) & \\log_2(x) - 3", r: "\\log_2(x) - 3" },
    { q: "\\log_b(x^5)", estrategia: "Propiedad de la potencia: el exponente baja a multiplicar.", pasos: "1) & 5 \\cdot \\log_b(x)", r: "5 \\cdot \\log_b(x)" },
    { q: "\\log_5(x^2 y^3)", estrategia: "Aplicar producto y potencia.", pasos: "1) & \\log_5(x^2) + \\log_5(y^3) \\\\ 2) & 2\\log_5(x) + 3\\log_5(y)", r: "2\\log_5(x) + 3\\log_5(y)" },
    { q: "\\log_b(\\sqrt{x})", estrategia: "Convertir raíz a exponente fraccionario.", pasos: "1) & \\log_b(x^{1/2}) \\\\ 2) & \\frac{1}{2} \\log_b(x)", r: "\\frac{1}{2} \\log_b(x)" },
    { q: "\\log_{25}(5)", estrategia: "Expresar argumento como potencia de la base.", pasos: "1) & 25^{1/2} = 5 \\\\ 2) & 1/2", r: "1/2" },
    { q: "\\log_3(9x)", estrategia: "Expandir logaritmo.", pasos: "1) & \\log_3(9) + \\log_3(x) \\\\ 2) & 2 + \\log_3(x)", r: "2 + \\log_3(x)" },
    { q: "\\log_2(32)", estrategia: "Evaluar potencia de 2.", pasos: "1) & 2^5 = 32 \\\\ 2) & 5", r: "5" },
    { q: "\\ln(e^2)", estrategia: "Logaritmo natural y exponencial son inversos.", pasos: "1) & 2 \\cdot \\ln(e) \\\\ 2) & 2", r: "2" },
    { q: "\\log_{1/2}(x)", estrategia: "Cambio de base a 2.", pasos: "1) & \\frac{\\log_2(x)}{\\log_2(2^{-1})} \\\\ 2) & -\\log_2(x)", r: "-\\log_2(x)" }
];
 const bancoMixto = [
        { q: "\\sqrt{x^6} \\cdot x^2", estrategia: "Convertir raíz a potencia y sumar exponentes.", pasos: "1) & \\text{Raíz: } x^{6/2} = x^3 \\\\ 2) & \\text{Producto: } x^3 \\cdot x^2 \\\\ 3) & \\text{Resultado: } x^5", r: "x^5" },
        { q: "\\frac{(a^2)^4}{\\sqrt{a^2}}", estrategia: "Resolver potencia y raíz antes de dividir bases iguales.", pasos: "1) & \\text{Potencia: } a^8 \\\\ 2) & \\text{Raíz: } a^1 \\\\ 3) & \\text{Cociente: } a^7", r: "a^7" },
        { q: "\\log_2(\\sqrt{4})", estrategia: "Operar de adentro hacia afuera.", pasos: "1) & \\text{Radical: } \\sqrt{4} = 2 \\\\ 2) & \\text{Log: } \\log_2(2) \\\\ 3) & \\text{Res: } 1", r: "1" },
        { q: "x \\cdot \\log_3(27)", estrategia: "Evaluar el logaritmo como potencia.", pasos: "1) & \\text{Log: } 3^3=27 \\rightarrow 3 \\\\ 2) & \\text{Producto: } 3x", r: "3x" },
        { q: "\\sqrt{25x^4} + x^2", estrategia: "Extraer raíz numérica y variable.", pasos: "1) & \\text{Raíz: } 5x^2 \\\\ 2) & \\text{Suma: } 5x^2 + 1x^2 \\\\ 3) & \\text{Res: } 6x^2", r: "6x^2" },
        { q: "10^{\\log(x)} + x", estrategia: "Identidad fundamental de logaritmos.", pasos: "1) & \\text{Identidad: } x \\\\ 2) & \\text{Suma: } x + x", r: "2x" },
        { q: "\\sqrt[3]{x} \\cdot x^{2/3}", estrategia: "Unificar base usando potencias fraccionarias.", pasos: "1) & \\text{Potencias: } x^{1/3} \\cdot x^{2/3} \\\\ 2) & \\text{Suma: } x^{3/3} = x", r: "x" },
        { q: "\\log_b(b^2 \\cdot \\sqrt{b})", estrategia: "Sumar exponentes antes de aplicar logaritmo.", pasos: "1) & \\text{Exp: } b^2 \\cdot b^{0.5} = b^{2.5} \\\\ 2) & \\text{Res: } 2.5", r: "2.5" },
        { q: "\\frac{\\sqrt[4]{x^8}}{x^2}", estrategia: "Simplificar raíz y dividir cantidades iguales.", pasos: "1) & \\text{Raíz: } x^2 \\\\ 2) & \\text{Cociente: } 1", r: "1" },
        { q: "\\log_2(8^2)", estrategia: "Expresar argumento como potencia de base 2.", pasos: "1) & \\text{Pot: } 8^2 = 64 \\\\ 2) & \\text{Log: } \\log_2(64) = 6", r: "6" },
        { q: "\\sqrt{x^4} + \\log_3(9)", estrategia: "Resolver términos de forma independiente.", pasos: "1) & \\text{Raíz: } x^2 \\\\ 2) & \\text{Log: } 2 \\\\ 3) & \\text{Total: } x^2+2", r: "x^2+2" },
        { q: "\\frac{\\log_b(x^2)}{\\log_b(x)}", estrategia: "Usar propiedad de potencia del logaritmo.", pasos: "1) & \\text{Exp: } 2\\log_b(x) \\\\ 2) & \\text{Res: } 2", r: "2" },
        { q: "\\sqrt[3]{\\log_2(256)}", estrategia: "Calcular valor de adentro hacia afuera.", pasos: "1) & \\text{Log: } 8 \\\\ 2) & \\text{Raíz: } \\sqrt[3]{8} = 2", r: "2" },
        { q: "\\log_5(5x) - \\log_5(x)", estrategia: "Aplicar propiedad del cociente.", pasos: "1) & \\text{Coc: } \\log_5(5) \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "\\log_x(\\sqrt[3]{x^2})", estrategia: "Convertir raíz a exponente fraccionario.", pasos: "1) & \\text{Pot: } x^{2/3} \\\\ 2) & \\text{Res: } 2/3", r: "2/3" },
        { q: "\\ln(e^3) - \\log(100)", estrategia: "Resolver logaritmos naturales y decimales.", pasos: "1) & \\text{Log: } 3 - 2 \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "\\sqrt{\\log_3(81)}", estrategia: "Resolver el logaritmo primero.", pasos: "1) & \\text{Log: } 4 \\\\ 2) & \\text{Raíz: } 2", r: "2" },
        { q: "\\log_b(1/\\sqrt{b})", estrategia: "Convertir fracción a potencia negativa.", pasos: "1) & \\text{Pot: } b^{-0.5} \\\\ 2) & \\text{Res: } -0.5", r: "-0.5" },
        { q: "2^{\\log_2(x^3)}", estrategia: "Propiedad de cancelación de funciones.", pasos: "1) & \\text{Id: } x^3", r: "x^3" },
        { q: "\\frac{\\sqrt{x}\\cdot x^2}{x^{2.5}}", estrategia: "Sumar exponentes antes de dividir.", pasos: "1) & \\text{Arr: } x^{2.5} \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "\\sqrt[3]{x}\\cdot\\sqrt[6]{x^2}", estrategia: "Homogeneizar índices de raíces.", pasos: "1) & \\text{Exp: } x^{1/3}\\cdot x^{1/3} \\\\ 2) & \\text{Res: } x^{2/3}", r: "x^{2/3}" },
        { q: "\\log_2(\\sqrt{2}\\cdot\\sqrt{2})", estrategia: "Resolver radical primero.", pasos: "1) & \\text{Rad: } \\sqrt{4}=2 \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "\\frac{(x^a)^b}{x^{ab}}", estrategia: "Potencia de potencia.", pasos: "1) & \\text{Pot: } x^{ab} \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "\\sqrt[n]{x^{2n}}+\\log_x(x^2)", estrategia: "Resolver términos por separado.", pasos: "1) & \\text{Raíz: } x^2 \\\\ 2) & \\text{Log: } 2 \\\\ 3) & \\text{Res: } x^2+2", r: "x^2+2" },
        { q: "\\log_b(b\\sqrt{b})", estrategia: "Propiedad del producto.", pasos: "1) & \\text{Pot: } b^{1.5} \\\\ 2) & \\text{Res: } 1.5", r: "1.5" },
        { q: "(\\sqrt[4]{x})^2", estrategia: "Simplificar exponente.", pasos: "1) & \\text{Pot: } x^{2/4} \\\\ 2) & \\text{Res: } \\sqrt{x}", r: "\\sqrt{x}" },
        { q: "\\log(100/x)+\\log(x)", estrategia: "Propiedad de suma de logaritmos.", pasos: "1) & \\text{Prod: } \\log(100) \\\\ 2) & \\text{Res: } 2", r: "2" },
        { q: "\\sqrt{x}\\cdot\\sqrt{x}\\cdot\\sqrt{x}\\cdot\\sqrt{x}", estrategia: "Agrupar factores semejantes.", pasos: "1) & \\text{Par: } x \\cdot x \\\\ 2) & \\text{Res: } x^2", r: "x^2" },
        { q: "\\log_3(9^x)", estrategia: "Expresar base como potencia.", pasos: "1) & \\text{Log: } 2x \\\\ 2) & \\text{Res: } 2x", r: "2x" },
        { q: "\\frac{\\sqrt[3]{a}}{a^{-2/3}}", estrategia: "Resta de exponentes.", pasos: "1) & \\text{Exp: } 1/3 - (-2/3) \\\\ 2) & \\text{Res: } a", r: "a" },
        { q: "\\log_b(1)+\\sqrt{x^0}", estrategia: "Evaluación de casos especiales.", pasos: "1) & \\text{Log: } 0, \\text{ Raíz: } 1 \\\\ 2) & \\text{Res: } 1", r: "1" },
        { q: "x^{0.5}\\cdot\\sqrt{x^3}", estrategia: "Suma de exponentes.", pasos: "1) & \\text{Exp: } 0.5+1.5 \\\\ 2) & \\text{Res: } x^2", r: "x^2" },
        { q: "\\log_2(1/8)", estrategia: "Logaritmo de base negativa.", pasos: "1) & \\text{Pot: } 2^{-3} \\\\ 2) & \\text{Res: } -3", r: "-3" },
        { q: "\\sqrt[3]{x^2}\\cdot x^{1/3}", estrategia: "Suma de fracciones.", pasos: "1) & \\text{Exp: } 2/3 + 1/3 \\\\ 2) & \\text{Res: } x", r: "x" },
        { q: "\\log_b(x^n)-n\\log_b(x)", estrategia: "Propiedad del logaritmo de potencia.", pasos: "1) & \\text{Prop: } n\\log_b(x) \\\\ 2) & \\text{Res: } 0", r: "0" },
        { q: "\\sqrt{x^2 y^4 z^6}", estrategia: "Raíz de cada factor.", pasos: "1) & \\text{Div: } x y^2 z^3", r: "xy^2z^3" },
        { q: "\\log_2(4x)-\\log_2(x)", estrategia: "Cociente de argumentos.", pasos: "1) & \\text{Coc: } \\log_2(4) \\\\ 2) & \\text{Res: } 2", r: "2" },
        { q: "(x \\cdot x^2 \\cdot x^3)^{1/3}", estrategia: "Operar interior y luego exponente.", pasos: "1) & \\text{Int: } x^6 \\\\ 2) & \\text{Multiplica: } x^2", r: "x^2" },
        { q: "\\sqrt[3]{a}\\cdot\\sqrt[3]{a}\\cdot\\sqrt[3]{a}", estrategia: "Cubicar el radical.", pasos: "1) & \\text{Rad: } (\\sqrt[3]{a})^3 \\\\ 2) & \\text{Res: } a", r: "a" },
        { q: "\\log_{10}(\\sqrt[5]{10})", estrategia: "Definición del logaritmo.", pasos: "1) & \\text{Pot: } 10^{0.2} \\\\ 2) & \\text{Res: } 0.2", r: "0.2" },
        { q: "\\frac{x^n \\cdot x^2}{x^{n-1}}", estrategia: "Álgebra de exponentes.", pasos: "1) & \\text{Arr: } x^{n+2} \\\\ 2) & \\text{Resta: } x^3", r: "x^3" },
        { q: "\\sqrt{x^4/y^2}", estrategia: "Distributiva de la raíz.", pasos: "1) & \\text{Raíz: } x^2/y", r: "x^2/y" },
        { q: "\\log_3(3)+\\log_3(1)+\\log_3(1/3)", estrategia: "Sumatoria de valores.", pasos: "1) & \\text{Valores: } 1+0-1 \\\\ 2) & \\text{Res: } 0", r: "0" },
        { q: "\\sqrt[n]{x^n y^{2n}}", estrategia: "División por el índice n.", pasos: "1) & \\text{Div: } x y^2", r: "xy^2" },
        { q: "\\log_2(x^2)+\\log_2(1/x)", estrategia: "Propiedad del producto.", pasos: "1) & \\text{Prod: } \\log_2(x) \\\\ 2) & \\text{Res: } \\log_2(x)", r: "\\log_2(x)" },
        { q: "\\sqrt[4]{16x^8}", estrategia: "Extraer raíz 4ta.", pasos: "1) & \\text{Res: } 2x^2", r: "2x^2" },
        { q: "\\log_3(\\sqrt{3}^x)", estrategia: "Potencia de base 3.", pasos: "1) & \\text{Exp: } x/2 \\\\ 2) & \\text{Res: } x/2", r: "x/2" },
        { q: "\\frac{x^2\\sqrt{x}}{x}", estrategia: "Simplificar términos.", pasos: "1) & \\text{Exp: } x \\cdot x^{0.5} \\\\ 2) & \\text{Res: } x^{1.5}", r: "x^{1.5}" },
        { q: "\\log_4(2^x)", estrategia: "Cambio de base a 2.", pasos: "1) & \\text{Base: } \\log_{2^2}(2^x) \\\\ 2) & \\text{Res: } x/2", r: "x/2" },
        { q: "\\sqrt[3]{x^3\\sqrt{x^6}}", estrategia: "Jerarquía de radicales.", pasos: "1) & \\text{Int: } \\sqrt{x^6}=x^3 \\\\ 2) & \\text{Total: } \\sqrt[3]{x^6}=x^2", r: "x^2" }
    ];
